### ISSUE TITLE
プライベートリポジトリに対応

### ISSUE THREAD

**Issue by Yuta-Hachino** [unbereal/react-issue-ganttchart#1]
```yaml
start_date: 2021/9/28
due_date: 2021/9/28
progress: 0.1
parent: 0
```
