### ISSUE TITLE
ガントチャート用パラメータがissue内容に含まれていない場合、パラメーターを追加する。

### ISSUE THREAD

**Issue by Yuta-Hachino** [unbereal/react-issue-ganttchart#2]
```yaml
start_date: 2021/9/28
due_date: 2021/9/28
progress: 0.1
parent: 0
```
